### ISSUE TITLE
What do you think to write down some usage instructions?

### ISSUE THREAD

**Issue by moacirosa** [dynamoxteam/advent-of-code#1]
I'm not used with Rust and its ecosystem. However I'd like to run the `answer` and the `tests` at least as curiosity. What do you think? As an example I tried to write some _Usage_  and _Test_ instructions for our [JS implementation](https://github.com/dynamoxteam/advent-of-code/tree/master/2017/js/day01#usage).

**Comment by Milack27** [comment]
Sure, that's a good idea. In Rust, the usage instructions are gonna be kind of `cargo run <input>`, where `<input>` is a string or a file, if it's too large to type it manually. But it's a good thing to put in a readme.md anyway.

**Comment by moacirosa** [comment]
It was resolved in #6823152dd4004b3214976b61f6c499bffde94971
